[package]
name = "phatdev"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.dev]
debug = true

[package.metadata.wasm-pack.profile.release]
debug = false
